### GENERAL
server:
  port: 8082

## PostgreSQL
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: docker
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


pl:
  mkotynski:
    mfms:
     app-name: MMF

###
#keycloak.auth-server-url = 'http://127.0.0.1:8081/auth/'
#keycloak.realm = 'MedicalFacilityManagementSystem'
#keycloak.resource = 'mfms-spring-client'
#keycloak.public-client = true

#keycloak:
#  enabled: true
#  auth-server-url: http://localhost:8080/auth
#  realm: MedicalFacilityManagementSystem
#  resource: mfms-spring-client
#  public-client: true
#  security-constraints:
#    - securityCollections:
#        - name: public resource
#          patterns:
#            - /api/keycloak/config

keycloak:
  realm: MFMS
  auth-server-url: http://localhost:8080/auth
  ssl-required : external
  resource: mfms-spring-client
  use-resource-role-mappings: true
  bearer-only: true
  principal-attribute: preferred_username
  cors: true
