### GENERAL
server:
  port: 8085

## PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: mfms-backend
    password: mfms-backend
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

pl:
  mkotynski:
    mfms:
     app-name: MMF

#Keycloak connection parameters
keycloak:
  realm: mfms
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: mfms-service
  credentials:
    secret: bed964a6-27a5-4134-a081-f7fe5c55c0cb
  use-resource-role-mappings: true
  bearer-only: true